gamemode = 'pump-double'

drummap = {
    'Acoustic Bass Drum': 35,
    'Bass Drum 1': 36,
    'Side Stick': 37,
    'Acoustic Snare': 38,
    'Hand Clap': 39,
    'Electric Snare': 40,
    'Low Floor Tom': 41,
    'Closed Hi Hat': 42,
    'High Floor Tom': 43,
    'Pedal Hi-Hat': 44,
    'Low Tom': 45,
    'Open Hi-Hat': 46,
    'Low-Mid Tom': 47,
    'Hi-Mid Tom': 48,
    'Crash Cymbal 1': 49,
    'High Tom': 50,
    'Ride Cymbal 1': 51,
    'Chinese Cymbal': 52,
    'Ride Bell': 53,
    'Tambourine': 54,
    'Splash Cymbal': 55,
    'Cowbell': 56,
    'Crash Cymbal 2': 57,
    'Vibraslap': 58,
    'Ride Cymbal 2': 59,
    'Hi Bongo': 60,
    'Low Bongo': 61,
    'Mute Hi Conga': 62,
    'Open Hi Conga': 63,
    'Low Conga': 64,
    'High Timbale': 65,
    'Low Timbale': 66,
    'High Agogo': 67,
    'Low Agogo': 68,
    'Cabasa': 69,
    'Maracas': 70,
    'Short Whistle': 71,
    'Long Whistle': 72,
    'Short Guiro': 73,
    'Long Guiro': 74,
    'Claves': 75,
    'Hi Wood Block': 76,
    'Low Wood Block': 77,
    'Mute Cuica': 78,
    'Open Cuica': 79,
    'Mute Triangle': 80,
    'Open Triangle': 81,
}

gamemodes = {
    'gddm-old': {
        'left cymbal': 0,
        'snare': 1,
        'kick pedal': 2,
        'high tom': 3,
        'low tom': 4,
        'right cymbal': 5
    },
    'gddm-new': {
        'left cymbal': 0,
        'hi-hat': 1,
        'left pedal': 2,
        'snare': 3,
        'high tom': 4,
        'kick pedal': 5,
        'low tom': 6,
        'floor tom': 7,
        'right cymbal': 8
    },
    'gddm-real': {
        'left cymbal': 0,
        'hi-hat': 1,
        'left pedal': 2,
        'snare': 3,
        'high tom': 4,
        'kick pedal': 5,
        'low tom': 6,
        'floor tom': 7,
        'ride': 8,
        'right cymbal': 9
    },
}

midi_to_gddm = {
    drummap['Acoustic Bass Drum']: gamemodes['gddm-real']['kick pedal'],
    drummap['Bass Drum 1']: gamemodes['gddm-real']['kick pedal'],
    drummap['Side Stick']: gamemodes['gddm-real']['snare'],
    drummap['Acoustic Snare']: gamemodes['gddm-real']['snare'],
    drummap['Hand Clap']: gamemodes['gddm-real']['high tom'],
    drummap['Electric Snare']: gamemodes['gddm-real']['snare'],
    drummap['Low Floor Tom']: gamemodes['gddm-real']['floor tom'],
    drummap['Closed Hi Hat']: gamemodes['gddm-real']['hi-hat'],
    drummap['High Floor Tom']: gamemodes['gddm-real']['floor tom'],
    drummap['Pedal Hi-Hat']: gamemodes['gddm-real']['left pedal'],
    drummap['Low Tom']: gamemodes['gddm-real']['low tom'],
    drummap['Open Hi-Hat']: gamemodes['gddm-real']['hi-hat'],
    drummap['Low-Mid Tom']: gamemodes['gddm-real']['low tom'],
    drummap['Hi-Mid Tom']: gamemodes['gddm-real']['high tom'],
    drummap['Crash Cymbal 1']: gamemodes['gddm-real']['left cymbal'],
    drummap['High Tom']: gamemodes['gddm-real']['high tom'],
    drummap['Ride Cymbal 1']: gamemodes['gddm-real']['ride'],
    drummap['Chinese Cymbal']: gamemodes['gddm-real']['right cymbal'],
    drummap['Ride Bell']: gamemodes['gddm-real']['ride'],
    drummap['Tambourine']: gamemodes['gddm-real']['hi-hat'],
    drummap['Splash Cymbal']: gamemodes['gddm-real']['right cymbal'],
    drummap['Cowbell']: gamemodes['gddm-real']['high tom'],
    drummap['Crash Cymbal 2']: gamemodes['gddm-real']['right cymbal'],
    drummap['Vibraslap']: gamemodes['gddm-real']['right cymbal'],
    drummap['Ride Cymbal 2']: gamemodes['gddm-real']['ride'],
    drummap['Hi Bongo']: gamemodes['gddm-real']['high tom'],
    drummap['Low Bongo']: gamemodes['gddm-real']['low tom'],
    drummap['Mute Hi Conga']: gamemodes['gddm-real']['high tom'],
    drummap['Open Hi Conga']: gamemodes['gddm-real']['high tom'],
    drummap['Low Conga']: gamemodes['gddm-real']['low tom'],
    drummap['High Timbale']: gamemodes['gddm-real']['high tom'],
    drummap['Low Timbale']: gamemodes['gddm-real']['low tom'],
    drummap['High Agogo']: gamemodes['gddm-real']['high tom'],
    drummap['Low Agogo']: gamemodes['gddm-real']['low tom'],
    drummap['Cabasa']: gamemodes['gddm-real']['hi-hat'],
    drummap['Maracas']: gamemodes['gddm-real']['hi-hat'],
    # drummap['Short Whistle']: None,
    # drummap['Long Whistle']: None,
    # drummap['Short Guiro']: None,
    # drummap['Long Guiro']: None,
    drummap['Claves']: gamemodes['gddm-real']['low tom'],
    drummap['Hi Wood Block']: gamemodes['gddm-real']['high tom'],
    drummap['Low Wood Block']: gamemodes['gddm-real']['low tom'],
    # drummap['Mute Cuica']: None,
    # drummap['Open Cuica']: None,
    drummap['Mute Triangle']: gamemodes['gddm-real']['ride'],
    drummap['Open Triangle']: gamemodes['gddm-real']['ride']
}